### ISSUE TITLE
Does not work on ESXi 8.0-20513097

### ISSUE THREAD

**Issue by iBoostAI** [netgc/esxi-unlocker-4#2]
```
PatchSMC 4.0.2
==============
© 2014-2022 David Parsons
File: ./tmp/bin/vmx-debug
Traceback (most recent call last):
  File "./patchsmc", line 468, in <module>
    main()
  File "./patchsmc", line 454, in main
    f(filename)
  File "./patchsmc", line 244, in patchsmc
    osk0 = getdata(vmx, smc1_osk0, getkey(vmx, smc1_osk0))
  File "./patchsmc", line 113, in getkey
    vmx.seek(offset)
ValueError: seek out of range
PatchSMC 4.0.2
==============
© 2014-2022 David Parsons
File: ./tmp/bin/vmx-stats
Traceback (most recent call last):
  File "./patchsmc", line 468, in <module>
    main()
  File "./patchsmc", line 454, in main
    f(filename)
  File "./patchsmc", line 215, in patchsmc
    vmx = mmap.mmap(f.fileno(), 0)
ValueError: cannot mmap an empty file
Building apple.v00 VMTAR file...
tar: write error: No space left on device
pigz: write error code 28
pigz: abort: write error on apple.vtar.v00
mv: can't rename 'apple.vtar.v00': No such file or directory
Cleaning up tmp files...
Loading Apple support...
gunzip: apple.v00: No such file or directory
'gunzip -c apple.v00 >/tmp/filec1EpKe' failed with 256
Checking VMTAR loaded...
Failure apple.v00 not loaded
```

**Comment by netgc** [comment]
Work well!

Download ESXi 8.0 (integrated Unlocker & OEM BIOS)

Powered by [sysin.org](https://sysin.org/)

- [VMware ESXi 8.0U3 Unlocker standard & Custom Image](https://sysin.org/blog/vmware-esxi-8-u3-oem/)
- [VMware ESXi 8.0U3 Unlocker with driver](https://sysin.org/blog/vmware-esxi-8-u3-sysin/)
- [VMware ESXi 8.0U2 Unlocker standard & Custom Image](https://sysin.org/blog/vmware-esxi-8-u2-oem/)
- [VMware ESXi 8.0U2 Unlocker with driver](https://sysin.org/blog/vmware-esxi-8-u2-sysin/)
- [VMware ESXi 8.0U1 Unlocker standard & Custom Image](https://sysin.org/blog/vmware-esxi-8-u1-oem/)
- [VMware ESXi 8.0U1 Unlocker with driver](https://sysin.org/blog/vmware-esxi-8-u1-sysin/)
- [VMware ESXi 8.0 Unlocker standard & Custom Image](https://sysin.org/blog/vmware-esxi-8-oem/)
- [VMware ESXi 8.0 Unlocker with driver](https://sysin.org/blog/vmware-esxi-8-sysin/)

**Comment by NathObeaN** [comment]
Is it possible to get this to work on ESXi without a custom image? I am trying to get MacOS Sequoia working on ESXi-8.0U2-22380479 and  I don't want to reinstall ESXi for the sake of a single VM...

Thanks

**Comment by netgc** [comment]
> Is it possible to get this to work on ESXi without a custom image? I am trying to get MacOS Sequoia working on ESXi-8.0U2-22380479 and I don't want to reinstall ESXi for the sake of a single VM...
> 
> Thanks

You can upgrade it while keeping all configurations and virtual machines—just like with the standard edition of ESXi. It only takes a few minutes.

**Comment by NathObeaN** [comment]
Thanks, but I seemed to fix it by installing version 3 of the patch, and setting the VM to 7U2, all works ok now. The performance isn't great, maybe that is improved with v4 patch and/or above suggestion, but I only need it for testing purposes.
